### PR TITLE
chore(ci): add renovate config

### PR DESCRIPTION
**Pull request by shinGangan**
### 🔗 Linked issue

closed #24 .

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation or readme)
- [ ] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [x] 🧹 Chore (updates to the build process or auxiliary tools and libraries)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

Added `renovate.json`. Also, added a renove config for Nuxt.

- https://github.com/nuxt/renovate-config-nuxt

### CODE REVIEW

**Comment by shinGangan** [comment]
Hello @Gugustinette , please review when you have a time 🙏
This PR has low review priority.

**Comment by shinGangan** [comment]
Hi @Gugustinette , do you have any additional suggestions for this PR?
If it looks OK, I'd be happy if you could merge it.

**Comment by Gugustinette** [comment]
Yup that's my bad sorry for the late response 😭

**Comment by shinGangan** [comment]
@Gugustinette , thank you for merging this PR that your busy schedule! 🙏

**Pull request merged**
